##
## Copyright 2012 Google LLC
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; version 2 of the License.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##

depthcharge-$(CONFIG_DRIVER_INPUT_MKBP_KEYMATRIX_STANDARD_V10) += standard_v10.c
depthcharge-$(CONFIG_DRIVER_INPUT_MKBP_KEYMATRIX_STANDARD_V30) += standard_v30.c
depthcharge-$(CONFIG_DRIVER_INPUT_MKBP_KEYMATRIX_STANDARD_V30_TKL) += standard_v30_tkl.c
