##
## Copyright (c) 2019, Intel Corporation.
## Copyright 2019 Google Inc.
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; version 2 of the License.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##

depthcharge-$(CONFIG_DRIVER_BUS_I2S_INTEL_COMMON_I2S) += i2s.c
depthcharge-$(CONFIG_DRIVER_BUS_I2S_INTEL_COMMON_MAX98357A) += max98357a.c
depthcharge-$(CONFIG_DRIVER_BUS_I2S_INTEL_COMMON_MAX98390) += max98390.c
