##
## This file is part of the depthcharge project.
##
## Copyright 2013 Google Inc.
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; version 2 of the License.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
##

subdirs-$(CONFIG_BOARD_BOLT) += bolt
subdirs-$(CONFIG_BOARD_DAISY) += daisy
subdirs-$(CONFIG_BOARD_FALCO) += falco
subdirs-$(CONFIG_BOARD_FOX_BASKINGRIDGE) += fox_baskingridge
subdirs-$(CONFIG_BOARD_FOX_WTM2) += fox_wtm2
subdirs-$(CONFIG_BOARD_LINK) += link
subdirs-$(CONFIG_BOARD_LUMPY) += lumpy
subdirs-$(CONFIG_BOARD_PEACH_PIT) += peach_pit
subdirs-$(CONFIG_BOARD_PEPPY) += peppy
subdirs-$(CONFIG_BOARD_SLIPPY) += slippy
