/*
 * Copyright (C) 2018 Google Inc.
 * Copyright (C) 2018 Intel Corporation.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; version 2 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 */

#ifndef __DRIVERS_GPIO_GLK_DEFS_H__
#define __DRIVERS_GPIO_GLK_DEFS_H__

/* North West community pads */
/* For DFx GPIO, Display, USB, I2C, UART, and Thermal GPIO*/
#define NW_OFFSET                       0
#define GPIO_0                          (NW_OFFSET + 0)
#define GPIO_1                          (NW_OFFSET + 1)
#define GPIO_2                          (NW_OFFSET + 2)
#define GPIO_3                          (NW_OFFSET + 3)
#define GPIO_4                          (NW_OFFSET + 4)
#define GPIO_5                          (NW_OFFSET + 5)
#define GPIO_6                          (NW_OFFSET + 6)
#define GPIO_7                          (NW_OFFSET + 7)
#define GPIO_8                          (NW_OFFSET + 8)
#define GPIO_9                          (NW_OFFSET + 9)
#define GPIO_10                         (NW_OFFSET + 10)
#define GPIO_11                         (NW_OFFSET + 11)
#define GPIO_12                         (NW_OFFSET + 12)
#define GPIO_13                         (NW_OFFSET + 13)
#define GPIO_14                         (NW_OFFSET + 14)
#define GPIO_15                         (NW_OFFSET + 15)
#define GPIO_16                         (NW_OFFSET + 16)
#define GPIO_17                         (NW_OFFSET + 17)
#define GPIO_18                         (NW_OFFSET + 18)
#define GPIO_19                         (NW_OFFSET + 19)
#define GPIO_20                         (NW_OFFSET + 20)
#define GPIO_21                         (NW_OFFSET + 21)
#define GPIO_22                         (NW_OFFSET + 22)
#define GPIO_23                         (NW_OFFSET + 23)
#define GPIO_24                         (NW_OFFSET + 24)
#define GPIO_25                         (NW_OFFSET + 25)
#define GPIO_26                         (NW_OFFSET + 26)
#define GPIO_27                         (NW_OFFSET + 27)
#define GPIO_28                         (NW_OFFSET + 28)
#define GPIO_29                         (NW_OFFSET + 29)
#define GPIO_30                         (NW_OFFSET + 30)
#define GPIO_31                         (NW_OFFSET + 31)
#define GPIO_32                         (NW_OFFSET + 32)
#define GPIO_33                         (NW_OFFSET + 33)
#define GPIO_34                         (NW_OFFSET + 34)
#define GPIO_35                         (NW_OFFSET + 35)
#define GPIO_36                         (NW_OFFSET + 36)
#define GPIO_37                         (NW_OFFSET + 37)
#define GPIO_38                         (NW_OFFSET + 38)
#define GPIO_39                         (NW_OFFSET + 39)
#define GPIO_40                         (NW_OFFSET + 40)
#define GPIO_41                         (NW_OFFSET + 41)
#define GPIO_42                         (NW_OFFSET + 42)
#define GPIO_43                         (NW_OFFSET + 43)
#define GPIO_44                         (NW_OFFSET + 44)
#define GPIO_45                         (NW_OFFSET + 45)
#define GPIO_46                         (NW_OFFSET + 46)
#define GPIO_47                         (NW_OFFSET + 47)
#define GPIO_48                         (NW_OFFSET + 48)
#define GPIO_49                         (NW_OFFSET + 49)
#define GPIO_50                         (NW_OFFSET + 50)
#define GPIO_51                         (NW_OFFSET + 51)
#define GPIO_52                         (NW_OFFSET + 52)
#define GPIO_53                         (NW_OFFSET + 53)
#define GPIO_54                         (NW_OFFSET + 54)
#define GPIO_55                         (NW_OFFSET + 55)
#define GPIO_56                         (NW_OFFSET + 56)
#define GPIO_57                         (NW_OFFSET + 57)
#define GPIO_58                         (NW_OFFSET + 58)
#define GPIO_59                         (NW_OFFSET + 59)
#define GPIO_60                         (NW_OFFSET + 60)
#define GPIO_61                         (NW_OFFSET + 61)
#define GPIO_62                         (NW_OFFSET + 62)
#define GPIO_63                         (NW_OFFSET + 63)
#define GPIO_64                         (NW_OFFSET + 64)
#define GPIO_65                         (NW_OFFSET + 65)
#define GPIO_66                         (NW_OFFSET + 66)
#define GPIO_67                         (NW_OFFSET + 67)
#define GPIO_68                         (NW_OFFSET + 68)
#define GPIO_69                         (NW_OFFSET + 69)
#define GPIO_70                         (NW_OFFSET + 70)
#define GPIO_71                         (NW_OFFSET + 71)
#define GPIO_72                         (NW_OFFSET + 72)
#define GPIO_73                         (NW_OFFSET + 73)
#define GPIO_74                         (NW_OFFSET + 74)
#define GPIO_75                         (NW_OFFSET + 75)
#define GPIO_211                        (NW_OFFSET + 76)
#define GPIO_212                        (NW_OFFSET + 77)
#define GPIO_213                        (NW_OFFSET + 78)
#define GPIO_214                        (NW_OFFSET + 79)

/* North Community Pads */
/* For power management GPIO, I2C, Display, LPC/eSPI, SPI */
#define N_OFFSET                        (NW_OFFSET + 80)
#define GPIO_76                         (N_OFFSET + 0)
#define GPIO_77                         (N_OFFSET + 1)
#define GPIO_78                         (N_OFFSET + 2)
#define GPIO_79                         (N_OFFSET + 3)
#define GPIO_80                         (N_OFFSET + 4)
#define GPIO_81                         (N_OFFSET + 5)
#define GPIO_82                         (N_OFFSET + 6)
#define GPIO_83                         (N_OFFSET + 7)
#define GPIO_84                         (N_OFFSET + 8)
#define GPIO_85                         (N_OFFSET + 9)
#define GPIO_86                         (N_OFFSET + 10)
#define GPIO_87                         (N_OFFSET + 11)
#define GPIO_88                         (N_OFFSET + 12)
#define GPIO_89                         (N_OFFSET + 13)
#define GPIO_90                         (N_OFFSET + 14)
#define GPIO_91                         (N_OFFSET + 15)
#define GPIO_92                         (N_OFFSET + 16)
#define GPIO_93                         (N_OFFSET + 17)
#define GPIO_94                         (N_OFFSET + 18)
#define GPIO_95                         (N_OFFSET + 19)
#define GPIO_96                         (N_OFFSET + 20)
#define GPIO_97                         (N_OFFSET + 21)
#define GPIO_98                         (N_OFFSET + 22)
#define GPIO_99                         (N_OFFSET + 23)
#define GPIO_100                        (N_OFFSET + 24)
#define GPIO_101                        (N_OFFSET + 25)
#define GPIO_102                        (N_OFFSET + 26)
#define GPIO_103                        (N_OFFSET + 27)
#define GPIO_104                        (N_OFFSET + 28)
#define GPIO_105                        (N_OFFSET + 29)
#define GPIO_106                        (N_OFFSET + 30)
#define GPIO_107                        (N_OFFSET + 31)
#define GPIO_108                        (N_OFFSET + 32)
#define GPIO_109                        (N_OFFSET + 33)
#define GPIO_110                        (N_OFFSET + 34)
#define GPIO_111                        (N_OFFSET + 35)
#define GPIO_112                        (N_OFFSET + 36)
#define GPIO_113                        (N_OFFSET + 37)
#define GPIO_114                        (N_OFFSET + 38)
#define GPIO_115                        (N_OFFSET + 39)
#define GPIO_116                        (N_OFFSET + 40)
#define GPIO_117                        (N_OFFSET + 41)
#define GPIO_118                        (N_OFFSET + 42)
#define GPIO_119                        (N_OFFSET + 43)
#define GPIO_120                        (N_OFFSET + 44)
#define GPIO_121                        (N_OFFSET + 45)
#define GPIO_122                        (N_OFFSET + 46)
#define GPIO_123                        (N_OFFSET + 47)
#define GPIO_124                        (N_OFFSET + 48)
#define GPIO_125                        (N_OFFSET + 49)
#define GPIO_126                        (N_OFFSET + 50)
#define GPIO_127                        (N_OFFSET + 51)
#define GPIO_128                        (N_OFFSET + 52)
#define GPIO_129                        (N_OFFSET + 53)
#define GPIO_130                        (N_OFFSET + 54)
#define GPIO_131                        (N_OFFSET + 55)
#define GPIO_132                        (N_OFFSET + 56)
#define GPIO_133                        (N_OFFSET + 57)
#define GPIO_134                        (N_OFFSET + 58)
#define GPIO_135                        (N_OFFSET + 59)
#define GPIO_136                        (N_OFFSET + 60)
#define GPIO_137                        (N_OFFSET + 61)
#define GPIO_138                        (N_OFFSET + 62)
#define GPIO_139                        (N_OFFSET + 63)
#define GPIO_140                        (N_OFFSET + 64)
#define GPIO_141                        (N_OFFSET + 65)
#define GPIO_142                        (N_OFFSET + 66)
#define GPIO_143                        (N_OFFSET + 67)
#define GPIO_144                        (N_OFFSET + 68)
#define GPIO_145                        (N_OFFSET + 69)
#define GPIO_146                        (N_OFFSET + 70)
#define GPIO_147                        (N_OFFSET + 71)
#define GPIO_148                        (N_OFFSET + 72)
#define GPIO_149                        (N_OFFSET + 73)
#define GPIO_150                        (N_OFFSET + 74)
#define GPIO_151                        (N_OFFSET + 75)
#define GPIO_152                        (N_OFFSET + 76)
#define GPIO_153                        (N_OFFSET + 77)
#define GPIO_154                        (N_OFFSET + 78)
#define GPIO_155                        (N_OFFSET + 79)

/* Audio Community Pads */
#define AUDIO_OFFSET                    (N_OFFSET + 80)
#define GPIO_156                        (AUDIO_OFFSET + 0)
#define GPIO_157                        (AUDIO_OFFSET + 1)
#define GPIO_158                        (AUDIO_OFFSET + 2)
#define GPIO_159                        (AUDIO_OFFSET + 3)
#define GPIO_160                        (AUDIO_OFFSET + 4)
#define GPIO_161                        (AUDIO_OFFSET + 5)
#define GPIO_162                        (AUDIO_OFFSET + 6)
#define GPIO_163                        (AUDIO_OFFSET + 7)
#define GPIO_164                        (AUDIO_OFFSET + 8)
#define GPIO_165                        (AUDIO_OFFSET + 9)
#define GPIO_166                        (AUDIO_OFFSET + 10)
#define GPIO_167                        (AUDIO_OFFSET + 11)
#define GPIO_168                        (AUDIO_OFFSET + 12)
#define GPIO_169                        (AUDIO_OFFSET + 13)
#define GPIO_170                        (AUDIO_OFFSET + 14)
#define GPIO_171                        (AUDIO_OFFSET + 15)
#define GPIO_172                        (AUDIO_OFFSET + 16)
#define GPIO_173                        (AUDIO_OFFSET + 17)
#define GPIO_174                        (AUDIO_OFFSET + 18)
#define GPIO_175                        (AUDIO_OFFSET + 19)

/* SCC community pads */
/* For SMBus, SD-Card, Clock, CNV/SDIO, eMMC */
#define SCC_OFFSET                      (AUDIO_OFFSET + 20)
#define GPIO_176                        (SCC_OFFSET + 0)
#define GPIO_177                        (SCC_OFFSET + 1)
#define GPIO_178                        (SCC_OFFSET + 2)
#define GPIO_187                        (SCC_OFFSET + 3)
#define GPIO_179                        (SCC_OFFSET + 4)
#define GPIO_180                        (SCC_OFFSET + 5)
#define GPIO_181                        (SCC_OFFSET + 6)
#define GPIO_182                        (SCC_OFFSET + 7)
#define GPIO_183                        (SCC_OFFSET + 8)
#define GPIO_184                        (SCC_OFFSET + 9)
#define GPIO_185                        (SCC_OFFSET + 10)
#define GPIO_186                        (SCC_OFFSET + 11)
#define GPIO_188                        (SCC_OFFSET + 12)
#define GPIO_210                        (SCC_OFFSET + 13)
#define GPIO_189                        (SCC_OFFSET + 14)
#define GPIO_190                        (SCC_OFFSET + 15)
#define GPIO_191                        (SCC_OFFSET + 16)
#define GPIO_192                        (SCC_OFFSET + 17)
#define GPIO_193                        (SCC_OFFSET + 18)
#define GPIO_194                        (SCC_OFFSET + 19)
#define GPIO_195                        (SCC_OFFSET + 20)
#define GPIO_196                        (SCC_OFFSET + 21)
#define GPIO_197                        (SCC_OFFSET + 22)
#define GPIO_198                        (SCC_OFFSET + 23)
#define GPIO_199                        (SCC_OFFSET + 24)
#define GPIO_200                        (SCC_OFFSET + 25)
#define GPIO_201                        (SCC_OFFSET + 26)
#define GPIO_202                        (SCC_OFFSET + 27)
#define GPIO_203                        (SCC_OFFSET + 28)
#define GPIO_204                        (SCC_OFFSET + 29)
#define GPIO_205                        (SCC_OFFSET + 30)
#define GPIO_206                        (SCC_OFFSET + 31)
#define GPIO_207                        (SCC_OFFSET + 32)
#define GPIO_208                        (SCC_OFFSET + 33)
#define GPIO_209                        (SCC_OFFSET + 34)

/* PCR PIDs. */
#define PCH_PCR_PID_GPIO_SCC            0xc8
#define PCH_PCR_PID_GPIO_AUDIO          0xc9
#define PAD_CFG_DW_OFFSET               0x600
#define PAD_CFG_DW_OFFSET_MUL           16

#endif /* __DRIVERS_GPIO_GLK_DEFS_H__ */
