##
## Copyright 2012 Google Inc.
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; version 2 of the License.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##

depthcharge-y += cleanup_funcs.c
depthcharge-y += device_tree.c
depthcharge-y += dt_set_macs.c
depthcharge-y += dt_set_wifi_calibration.c
depthcharge-y += gpt.c
depthcharge-y += graphics.c
depthcharge-y += init_funcs.c
depthcharge-y += list.c
depthcharge-y += ranges.c
depthcharge-y += state_machine.c
depthcharge-y += timestamp.c
